### ISSUE TITLE
Gender identifiers for detectives not joining in InDesign for default skin tone

### ISSUE THREAD

**Issue by erniemarch** [adobe-fonts/noto-emoji-svg#69]
Gender identifiers for detectives not joining in InDesign for default skin tone in

1F575 FE0F 200D 2642 FE0F    and    1F575 FE0F 200D 2640 FE0F

**Comment by misbatabassum** [comment]
Gender identifiers for detectives joining in InDesign (version 16.2.1) for default skin tone

![Screen Shot 2021-07-27 at 7 50 43 AM](https://user-images.githubusercontent.com/84794818/127176086-7f727ce7-3282-4f3e-b02b-eb07bd6a9c2b.png)
