### ISSUE TITLE
Rainbow flag components not joining in InDesign

### ISSUE THREAD

**Issue by erniemarch** [adobe-fonts/noto-emoji-svg#70]
Rainbow flag components not joining correctly in InDesign in imported test.txt file.

1F3F3 FE0F 200D 1F308

**Comment by misbatabassum** [comment]
Rainbow flag components are joining in InDesign (version 16.2.1)
![Screen Shot 2021-07-27 at 7 42 16 AM](https://user-images.githubusercontent.com/84794818/127174643-80080f69-db0c-4b62-851f-96ff8afb982c.png)
