### ISSUE TITLE
License not defined

### ISSUE THREAD

**Issue by pgassmann** [adobe-fonts/noto-emoji-svg#82]
Currently the License of this project, scripts and resources are not defined.

Some folders contain License (svg), but some don't (e.g. flags), some scripts contain copyright headers but no license.

Can the flag svg files be used? What's the Licence of the font?

**Comment by pgassmann** [comment]
Google Noto Emoji Project License Definition: https://github.com/googlefonts/noto-emoji#license

**Comment by frankrolf** [comment]
Hope this clears up any concerns!
